name:                lopt
version:             0.1.0.0
synopsis:            Optimal lambda calculus implementations
homepage:            https://github.com/cwgoes/juvix#readme
license:             BSD3
author:              Christopher Goes
maintainer:          cwgoes@pluranimity.org
copyright:           2019 Christopher Goes
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - protolude
  - text

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - NoMonomorphismRestriction
  - RankNTypes
  - LambdaCase
  - UnicodeSyntax
  - GADTs
  - ScopedTypeVariables
  - DeriveGeneric
  - DeriveAnyClass
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - DataKinds
  - GeneralizedNewtypeDeriving
  - DefaultSignatures
  - QuasiQuotes
  - TypeOperators
  - MultiParamTypeClasses
  - MultiWayIf

ghc-options:
  - -ferror-spans
  - -Wall
  - -fno-warn-orphans
  - -fno-warn-name-shadowing
  - -j4

library:
  source-dirs: src
  dependencies:
    - containers
  exposed-modules:
    - InteractionNet

executables:
  lopt:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - lopt
