---
kind: pipeline
type: docker
name: juvix-ci-build-pr

workspace:
  path: /drone/workspace

environment:
  STACK_ROOT: /drone/workspace/.stack

steps:
  - name: script-integrity-check
    image: alpine/git:v2.30.1
    pull: if-not-exists
    commands:
      - echo "464e715db89429f4cf5766f6c288f0b0b3ea65fcdc9b52cabeae4107e7dcb9d8  scripts/pre-run.sh" | sha256sum -c -
      - sh ./scripts/pre-run.sh

  - name: restore-cache
    image: meltwater/drone-cache
    pull: if-not-exists
    settings:
      backend: "s3"
      restore: true
      bucket: juvix-drone-cache
      region: eu-west-1
      cache_key: "{{ checksum \"stack.yaml\" }}"
      archive_format: "gzip"
      mount:
        - ./.stack-work
        - ./.stack
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    depends_on:
      - script-integrity-check

  - name: test-suite
    image: 922271945067.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    commands:
      - make test
    depends_on:
      - restore-cache

  - name: rebuild-cache
    image: meltwater/drone-cache
    pull: if-not-exists
    settings:
      backend: "s3"
      bucket: juvix-drone-cache
      region: eu-west-1
      rebuild: true
      archive_format: "gzip"
      override: false
      cache_key: "{{ checksum \"stack.yaml\" }}"
      mount:
        - ./.stack-work
        - ./.stack
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    when:
      status:
        - success
        - failure
    depends_on:
      - test-suite

  - name: test-parser
    image: 922271945067.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    failure: fast
    commands:
      - make test-parser
    depends_on:
      - test-suite

  - name: test-typecheck
    image: 922271945067.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    failure: fast
    commands:
      - make test-typecheck
    depends_on:
      - test-suite

  - name: test-compile
    image: 922271945067.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    failure: fast
    commands:
      - make test-compile
    depends_on:
      - test-suite
  
  - name: org-generation-and-code-formatting
    image: 922271945067.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    failure: fast
    commands:
      - sh ./scripts/format-and-org-gen.sh   
    depends_on:
      - test-typecheck
      - test-compile
      - test-parser

  - name: push changes
    image: openanalytics/alpine-git-lfs-client
    pull: if-not-exists
    commands:
      - sh ./scripts/push-changes.sh
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    depends_on:
      - org-generation-and-code-formatting

trigger:
  event:
    - pull_request
---
kind: pipeline
type: docker
name: juvix-ci-build-push-develop

workspace:
  path: /drone/workspace

environment:
  STACK_ROOT: /drone/workspace/.stack

steps:
  - name: script-integrity-check
    image: alpine/git:v2.30.1
    pull: if-not-exists
    commands:
      - echo "464e715db89429f4cf5766f6c288f0b0b3ea65fcdc9b52cabeae4107e7dcb9d8  scripts/pre-run.sh" | sha256sum -c -
      - sh ./scripts/pre-run.sh 

  - name: restore-cache
    image: meltwater/drone-cache
    pull: if-not-exists
    settings:
      backend: "s3"
      restore: true
      bucket: juvix-drone-cache
      region: eu-west-1
      cache_key: "{{ checksum \"stack.yaml\" }}"
      archive_format: "gzip"
      mount:
        - ./.stack-work
        - ./.stack
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    depends_on:
      - script-integrity-check

  - name: test-suite
    image: 922271945067.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    commands:
      - make test
    depends_on:
      - restore-cache

  - name: rebuild-cache
    image: meltwater/drone-cache
    pull: if-not-exists
    settings:
      backend: "s3"
      bucket: juvix-drone-cache
      region: eu-west-1
      rebuild: true
      archive_format: "gzip"
      override: false
      cache_key: "{{ checksum \"stack.yaml\" }}"
      mount:
        - ./.stack-work
        - ./.stack
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    when:
      status:
        - success
        - failure
    depends_on:
      - test-suite

  - name: check-formatting
    image: 922271945067.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    failure: fast
    commands:
      - sh ./scripts/check-formatting.sh
    depends_on:
      - test-suite

  - name: check-org-gen
    image: 922271945067.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    failure: fast
    commands:
      - sh ./scripts/check-org-gen.sh
    depends_on:
      - test-suite

  - name: test-parser
    image: 922271945067.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    failure: fast
    commands:
      - make test-parser
    depends_on:
      - test-suite

  - name: test-typecheck
    image: 922271945067.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    failure: fast
    commands:
      - make test-typecheck
    depends_on:
      - test-suite

  - name: test-compile
    image: 922271945067.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    failure: fast
    commands:
      - make test-compile
    depends_on:
      - test-suite

trigger:
  event:
    - push
  branch:
    - develop
---
kind: signature
hmac: cb2c4627c097b7da64ebca5e0a80fa8fb6b9edada119e5f59b56577dcd1e2cea

...
