kind: pipeline
type: docker
name: juvix-ci

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./.stack-work

- name: setup-dependencies
  image: cryptiumlabs/juvix-ci-2
  commands:
  - make setup

- name: test-suite
  image: cryptiumlabs/juvix-ci-2
  commands:
  - make test

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./.stack-work

- name: check-formatting
  image: cryptiumlabs/juvix-ci-2
  commands:
  - sh ./scripts/check-formatting.sh

- name: check-org-gen
  image: cryptiumlabs/juvix-ci-2
  commands:
  - sh ./scripts/check-org-gen.sh

- name: test-parser
  image: cryptiumlabs/juvix-ci-2
  commands:
  - make test-parser

- name: test-typecheck
  image: cryptiumlabs/juvix-ci-2
  commands:
  - make test-typecheck

- name: test-compile
  image: cryptiumlabs/juvix-ci-2
  commands:
  - make test-compile

volumes:
  - name: cache
    host: 
      path: /tmp/cache
