---
kind: pipeline
type: docker
name: juvix-ci-build-pr

workspace:
  path: /drone/workspace
  GIT_LFS_SKIP_SMUDGE: "1"

environment:
  STACK_ROOT: /drone/workspace/.stack

steps:
  - name: script-integrity-check
    image: alpine/git:v2.30.1
    pull: if-not-exists
    commands:
      - echo "943041e97f3e66ecc7f0beafe0231601790436f03b13f2934140e69d3d0cea12  scripts/pre-run.sh" | sha256sum -c -
      - sh ./scripts/pre-run.sh

  - name: restore-cache
    image: meltwater/drone-cache
    pull: if-not-exists
    settings:
      backend: "s3"
      restore: true
      bucket: juvix-drone-cache-v2
      region: eu-west-1
      cache_key: "{{ checksum \"stack.yaml\" }}"
      archive_format: "gzip"
      mount:
        - ./.stack-work
        - ./.stack
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    depends_on:
      - script-integrity-check

  - name: test-suite
    image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    commands:
      - make test
    depends_on:
      - restore-cache

  - name: rebuild-cache
    image: meltwater/drone-cache
    pull: if-not-exists
    settings:
      backend: "s3"
      bucket: juvix-drone-cache-v2
      region: eu-west-1
      rebuild: true
      archive_format: "gzip"
      override: false
      cache_key: "{{ checksum \"stack.yaml\" }}"
      mount:
        - ./.stack-work
        - ./.stack
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    when:
      status:
        - success
        - failure
    depends_on:
      - test-suite

  - name: test-parser
    image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    failure: fast
    commands:
      - make test-parser
    depends_on:
      - test-suite

  - name: test-typecheck
    image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    failure: fast
    commands:
      - make test-typecheck
    depends_on:
      - test-suite

  - name: test-compile
    image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    failure: fast
    commands:
      - make test-compile
    depends_on:
      - test-suite
  
  - name: org-generation-and-code-formatting
    image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    failure: fast
    commands:
      - sh ./scripts/format-and-org-gen.sh   
    depends_on:
      - test-typecheck
      - test-compile
      - test-parser

  - name: push changes
    image: openanalytics/alpine-git-lfs-client
    pull: if-not-exists
    commands:
      - sh ./scripts/push-changes.sh
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    depends_on:
      - org-generation-and-code-formatting

trigger:
  event:
    - pull_request
---
kind: pipeline
type: docker
name: juvix-ci-build-push-develop

workspace:
  path: /drone/workspace

environment:
  STACK_ROOT: /drone/workspace/.stack
  GIT_LFS_SKIP_SMUDGE: "1"

steps:
  - name: script-integrity-check
    image: alpine/git:v2.30.1
    pull: if-not-exists
    commands:
      - echo "943041e97f3e66ecc7f0beafe0231601790436f03b13f2934140e69d3d0cea12  scripts/pre-run.sh" | sha256sum -c -
      - sh ./scripts/pre-run.sh 

  - name: restore-cache
    image: meltwater/drone-cache
    pull: if-not-exists
    settings:
      backend: "s3"
      restore: true
      bucket: juvix-drone-cache-v2
      region: eu-west-1
      cache_key: "{{ checksum \"stack.yaml\" }}"
      archive_format: "gzip"
      mount:
        - ./.stack-work
        - ./.stack
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    depends_on:
      - script-integrity-check

  - name: test-suite
    image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    commands:
      - make test
    depends_on:
      - restore-cache

  - name: rebuild-cache
    image: meltwater/drone-cache
    pull: if-not-exists
    settings:
      backend: "s3"
      bucket: juvix-drone-cache-v2
      region: eu-west-1
      rebuild: true
      archive_format: "gzip"
      override: false
      cache_key: "{{ checksum \"stack.yaml\" }}"
      mount:
        - ./.stack-work
        - ./.stack
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    when:
      status:
        - success
        - failure
    depends_on:
      - test-suite

  - name: check-formatting
    image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    failure: fast
    commands:
      - sh ./scripts/check-formatting.sh
    depends_on:
      - test-suite

  - name: check-org-gen
    image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    failure: fast
    commands:
      - sh ./scripts/check-org-gen.sh
    depends_on:
      - test-suite

  - name: test-parser
    image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    failure: fast
    commands:
      - make test-parser
    depends_on:
      - test-suite

  - name: test-typecheck
    image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    failure: fast
    commands:
      - make test-typecheck
    depends_on:
      - test-suite

  - name: test-compile
    image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix
    pull: if-not-exists
    failure: fast
    commands:
      - make test-compile
    depends_on:
      - test-suite

trigger:
  event:
    - push
  branch:
    - develop
---
kind: signature
hmac: 841b51b7384d6ba8dc3ccc87d38e6c9ebbd5388acda7d979cd31b03a1acd4537

...
