name:                juvix
version:             0.0.0.0
github:              "cryptiumlabs/juvix"
license:             GPL-3
homepage:            https://github.com/cryptiumlabs/juvix#readme
synopsis:            Juvix smart contract language compiler, debugging toolkit, & stateful deployment system
category:            Web3
description:         Please see the README on GitHub at <https://github.com/cryptiumlabs/juvix#readme>
author:              Cryptium Labs
maintainer:          cwgoes@cryptium.ch, jeremy@cryptium.ch, marty@cryptium.ch, andy@cryptium.ch
copyright:           2018 Christopher Goes, 2018-2019 Cryptium Labs

extra-source-files:
- README.md

dependencies:
  - base >= 4.11 && < 5
  - protolude
  - text
  - mtl
  - containers
  - unordered-containers
  - hashable
  - fgl
  - lens
  - parsec
  - attoparsec
  - attoparsec-expr
  - capability >= 0.2.0.0
  - fgl-visualize
  - enummapset
  - turtle
  - directory
  - llvm-hs
  - llvm-hs-pure
  - llvm-hs-pretty
  - bytestring
  - time
  - morley
  - bulletproofs
  - elliptic-curve
  - sonic
  - aeson
  - Cabal
  - extensible-data

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - NoMonomorphismRestriction
  - RankNTypes
  - LambdaCase
  - UnicodeSyntax
  - GADTs
  - ScopedTypeVariables
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - DataKinds
  - GeneralizedNewtypeDeriving
  - DefaultSignatures
  - QuasiQuotes
  - TypeOperators
  - MultiParamTypeClasses
  - MultiWayIf
  - TypeInType
  - DerivingVia
  - TypeApplications
  - StandaloneDeriving
  - FunctionalDependencies
  - PatternSynonyms
  - TypeFamilies
  - ConstraintKinds
  - EmptyDataDeriving
  - TemplateHaskell

ghc-options:
  - -ferror-spans
  - -Wall
  - -fno-warn-orphans
  - -fno-warn-name-shadowing
  - -fno-warn-missing-pattern-synonym-signatures
  - -j6
  - -static

library:
  source-dirs: src
  dependencies:
    - z3
    - derive-storable
    - derive-storable-plugin
    - jsonschema-gen
  exposed-modules:
    - Juvix
    - Juvix.Frontend.Types
    - Juvix.Frontend.Lexer
    - Juvix.Frontend.Parser
    - Juvix.Core
    - Juvix.Core.HR
    - Juvix.Core.HRAnn
    - Juvix.Core.IR
    - Juvix.Core.IRAnn
    - Juvix.Core.Erased
    - Juvix.Core.ErasedAnn
    - Juvix.Core.Erased.Evaluator
    - Juvix.Core.Erased.Util
    - Juvix.Core.Erased.Types
    - Juvix.Core.Erasure
    - Juvix.Core.Erasure.Algorithm
    - Juvix.Core.Erasure.Types
    - Juvix.Core.Usage
    - Juvix.Core.Types
    - Juvix.Core.Parameterisations.Naturals
    - Juvix.Core.Parameterisations.Unit
    - Juvix.Core.Parameterisations.All
    - Juvix.Core.EAC
    - Juvix.Core.EAC.Check
    - Juvix.Core.EAC.ConstraintGen
    - Juvix.Core.EAC.Solve
    - Juvix.Core.EAC.Types
    - Juvix.Core.EAC.Parser
    - Juvix.Core.EAC.Erasure
    - Juvix.Interpreter
    - Juvix.Interpreter.InteractionNet
    - Juvix.Interpreter.InteractionNet.Nets.Default
    - Juvix.Interpreter.InteractionNet.Nets.Combinators
    - Juvix.Interpreter.InteractionNet.Backends.Interface
    - Juvix.Interpreter.InteractionNet.Backends.Env
    - Juvix.Interpreter.InteractionNet.Backends.Graph
    - Juvix.Interpreter.InteractionNet.Backends.Maps
    - Juvix.Interpreter.InteractionNet.Parser
    - Juvix.Interpreter.InteractionNet.Translation
    - Juvix.Interpreter.InteractionNet.Type
    - Juvix.Interpreter.InteractionNet.Shared
    - Juvix.Interpreter.InteractionNet.Default
    - Juvix.Library
    - Juvix.Library.HashMap
    - Juvix.Library.PrettyPrint
    - Juvix.Visualize.Dot
    - Juvix.Visualize.Graph
    - Juvix.Encoding.Encoding
    - Juvix.Encoding.Mendler
    - Juvix.Encoding.Scott
    - Juvix.Encoding.Types
    - Juvix.INetIR
    - Juvix.INetIR.Types
    - Juvix.INetIR.JSON
    - Juvix.Backends
    - Juvix.Backends.Michelson
    - Juvix.Backends.Michelson.Parameterisation
    - Juvix.Backends.Michelson.Compilation
    - Juvix.Backends.Michelson.Compilation.Types
    - Juvix.Backends.Michelson.Compilation.VirtualStack
    - Juvix.Backends.Michelson.DSL.Instructions
    - Juvix.Backends.Michelson.DSL.InstructionsEff
    - Juvix.Backends.Michelson.DSL.Environment
    - Juvix.Backends.Michelson.DSL.Untyped
    - Juvix.Backends.Michelson.DSL.Utils
    - Juvix.Backends.Michelson.Optimisation
    - Juvix.Backends.Michelson.Contract
    - Juvix.Backends.ArithmeticCircuit
    - Juvix.Backends.ArithmeticCircuit.Parameterisation
    - Juvix.Backends.ArithmeticCircuit.Compilation
    - Juvix.Backends.ArithmeticCircuit.Compilation.Types
    - Juvix.Backends.LLVM
    - Juvix.Backends.LLVM.JIT
    - Juvix.Backends.LLVM.JIT.Types
    - Juvix.Backends.LLVM.JIT.Execution
    - Juvix.Backends.LLVM.Translation
    - Juvix.Backends.LLVM.Codegen.Constants
    - Juvix.Backends.LLVM.Codegen.Sum
    - Juvix.Backends.LLVM.Codegen.Types
    - Juvix.Backends.LLVM.Codegen.Shared
    - Juvix.Backends.LLVM.Codegen.Block
    - Juvix.Backends.LLVM.Codegen.Graph
    - Juvix.Backends.LLVM.Codegen.Graph.Debug
    - Juvix.Backends.LLVM.Codegen.Graph.Operations
    - Juvix.Backends.LLVM.Codegen.Graph.Definitions
    - Juvix.Backends.LLVM.Codegen
    - Juvix.Backends.LLVM.Net.API
    - Juvix.Backends.LLVM.Net.EAC
    - Juvix.Backends.LLVM.Net.EAC.Types
    - Juvix.Backends.LLVM.Net.EAC.Defs
    - Juvix.Backends.LLVM.Net.EAC.Debug
    - Juvix.Backends.LLVM.Net.Environment
    - Juvix.Backends.LLVM.Net.EAC.MonadEnvironment
    - Juvix.Backends.LLVM.DSL
  other-modules:
    - Juvix.Interpreter.InteractionNet.NodeInterface
    - Juvix.Core.Translate
    - Juvix.Core.Pipeline
    - Juvix.Core.Utility
    - Juvix.Core.IR.Types
    - Juvix.Core.IR.Types.Base
    - Juvix.Core.IR.Typechecker
    - Juvix.Core.IR.TransformExt
    - Juvix.Core.IR.Evaluator
    - Juvix.Core.HR.Parser
    - Juvix.Core.HR.Types
    - Juvix.Core.HRAnn.Types
    - Juvix.Core.HRAnn.Erasure
    - Juvix.Core.IRAnn.Types
    - Juvix.Core.IRAnn.Erasure
    - Juvix.Core.ErasedAnn.Types
    - Juvix.Core.ErasedAnn.Erasure

executables:
  juvix:
    source-dirs:      app
    main:             Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - juvix
      - optparse-applicative
      - ansi-wl-pprint
      - raw-strings-qq
      - yaml
      - aeson
      - haskeline
      - gitrev

tests:
  juvix-test:
    main:         Main.hs
    source-dirs:  test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - juvix
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - QuickCheck
      - temporary
      - raw-strings-qq
      - process
