name:                juvix
version:             0.0.0.0
github:              "cryptiumlabs/juvix"
license:             GPL-3
homepage:            https://github.com/cryptiumlabs/juvix#readme
synopsis:            Juvix smart contract language compiler, debugging toolkit, & stateful deployment system
category:            Web3
description:         Please see the README on GitHub at <https://github.com/cryptiumlabs/juvix#readme>
author:              Cryptium Labs
maintainer:          cwgoes@cryptium.ch, jeremy@cryptium.ch, marty@cryptium.ch, andy@cryptium.ch
copyright:           2018 Christopher Goes, 2018-2019 Cryptium Labs

extra-source-files:
- README.md

dependencies:
  - base >= 4.11 && < 5
  - protolude
  - directory
  - lens
  - Cabal
  - extensible-data
  - capability >= 0.2.0.0
  - standard-library
  - frontend
  - core
  - translate
  ###########################
  # Dependency for OS
  ###########################
  - turtle
  - time
  - filepath
  ###########################
  # Dependency for Arithmetic
  ###########################
  - bulletproofs
  - elliptic-curve
  - sonic
  - arithmetic-circuits
  - galois-field
  - crypto-numbers
  - pairing
  - MonadRandom
  ###########################
  # Dependency for Structs
  ###########################
  - text
  - mtl
  - containers
  - unordered-containers
  - hashable
  - fgl
  - fgl-visualize
  - bytestring
  - enummapset
  ###########################
  # Dependency for Parsers
  ###########################
  - parsec
  - attoparsec
  - attoparsec-expr
  - aeson
  ###########################
  # Dependency for LLVM
  ###########################
  - llvm-hs
  - llvm-hs-pure
  - llvm-hs-pretty
  ###########################
  # Dependency for Morley
  ###########################
  - morley
  - vinyl
  - singletons
  - fmt

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - NoMonomorphismRestriction
  - RankNTypes
  - LambdaCase
  - UnicodeSyntax
  - GADTs
  - ScopedTypeVariables
  - DeriveDataTypeable
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - DataKinds
  - GeneralizedNewtypeDeriving
  - DefaultSignatures
  - QuasiQuotes
  - TypeOperators
  - MultiParamTypeClasses
  - MultiWayIf
  - TypeInType
  - DerivingVia
  - TypeApplications
  - StandaloneDeriving
  - FunctionalDependencies
  - PatternSynonyms
  - TypeFamilies
  - ConstraintKinds
  - EmptyDataDeriving
  - TemplateHaskell
  - NamedFieldPuns
  - DisambiguateRecordFields
  - TupleSections
  - BlockArguments

ghc-options:
  - -ferror-spans
  - -Wall
  - -fno-warn-orphans
  - -fno-warn-name-shadowing
  - -fno-warn-missing-pattern-synonym-signatures
  - -j
  - -static
  - -fwrite-ide-info

when:
  condition: flag(incomplete-error)
  ghc-options:
    - -Werror=incomplete-patterns
    - -Werror=missing-fields
    - -Werror=missing-methods

flags:
  incomplete-error:
    description: >
      Incomplete patterns, missing record fields, and missing class methods are
      an error
    manual: true
    default: false

library:
  source-dirs: src
  dependencies:
    - z3
    - derive-storable
    - derive-storable-plugin
    - jsonschema-gen
  exposed-modules:
    - Juvix
    - Juvix.Pipeline
    - Juvix.Core
    - Juvix.Core.Pipeline
    - Juvix.Core.FromFrontend
    - Juvix.Interpreter
    - Juvix.Interpreter.InteractionNet
    - Juvix.Interpreter.InteractionNet.Nets.Default
    - Juvix.Interpreter.InteractionNet.Nets.Combinators
    - Juvix.Interpreter.InteractionNet.Backends.Interface
    - Juvix.Interpreter.InteractionNet.Backends.Env
    - Juvix.Interpreter.InteractionNet.Backends.Graph
    - Juvix.Interpreter.InteractionNet.Backends.Maps
    - Juvix.Interpreter.InteractionNet.Parser
    - Juvix.Interpreter.InteractionNet.Translation
    - Juvix.Interpreter.InteractionNet.Type
    - Juvix.Interpreter.InteractionNet.Shared
    - Juvix.Interpreter.InteractionNet.Default
    - Juvix.Visualize.Dot
    - Juvix.Visualize.Graph
    - Juvix.Encoding.Encoding
    - Juvix.Encoding.Mendler
    - Juvix.Encoding.Scott
    - Juvix.Encoding.Types
    - Juvix.INetIR
    - Juvix.INetIR.Types
    - Juvix.INetIR.JSON
    - Juvix.Backends
    - Juvix.Backends.Michelson
    - Juvix.Backends.Michelson.Parameterisation
    - Juvix.Backends.Michelson.Compilation
    - Juvix.Backends.Michelson.Compilation.Types
    - Juvix.Backends.Michelson.Compilation.VirtualStack
    - Juvix.Backends.Michelson.DSL.Instructions
    - Juvix.Backends.Michelson.DSL.InstructionsEff
    - Juvix.Backends.Michelson.DSL.Environment
    - Juvix.Backends.Michelson.DSL.Untyped
    - Juvix.Backends.Michelson.DSL.Contract
    - Juvix.Backends.Michelson.DSL.Interpret
    - Juvix.Backends.Michelson.DSL.Utils
    - Juvix.Backends.Michelson.Optimisation
    - Juvix.Backends.Michelson.Contract
    - Juvix.Backends.ArithmeticCircuit
    - Juvix.Backends.ArithmeticCircuit.ZKP
    - Juvix.Backends.ArithmeticCircuit.Groth
    - Juvix.Backends.ArithmeticCircuit.Parameterisation
    - Juvix.Backends.ArithmeticCircuit.Parameterisation.Booleans
    - Juvix.Backends.ArithmeticCircuit.Parameterisation.FieldElements
    - Juvix.Backends.ArithmeticCircuit.Parameterisation.Integers
    - Juvix.Backends.ArithmeticCircuit.Compilation
    - Juvix.Backends.ArithmeticCircuit.Compilation.Types
    - Juvix.Backends.ArithmeticCircuit.Compilation.Environment
    - Juvix.Backends.ArithmeticCircuit.Compilation.Memory
    - Juvix.Backends.LLVM
    - Juvix.Backends.LLVM.JIT
    - Juvix.Backends.LLVM.JIT.Types
    - Juvix.Backends.LLVM.JIT.Execution
    - Juvix.Backends.LLVM.Translation
    - Juvix.Backends.LLVM.Codegen.Constants
    - Juvix.Backends.LLVM.Codegen.Sum
    - Juvix.Backends.LLVM.Codegen.Types
    - Juvix.Backends.LLVM.Codegen.Shared
    - Juvix.Backends.LLVM.Codegen.Block
    - Juvix.Backends.LLVM.Codegen.Graph
    - Juvix.Backends.LLVM.Codegen.Graph.Debug
    - Juvix.Backends.LLVM.Codegen.Graph.Operations
    - Juvix.Backends.LLVM.Codegen.Graph.Definitions
    - Juvix.Backends.LLVM.Codegen
    - Juvix.Backends.LLVM.Net.API
    - Juvix.Backends.LLVM.Net.EAC
    - Juvix.Backends.LLVM.Net.EAC.Types
    - Juvix.Backends.LLVM.Net.EAC.Defs
    - Juvix.Backends.LLVM.Net.EAC.Debug
    - Juvix.Backends.LLVM.Net.Environment
    - Juvix.Backends.LLVM.Net.EAC.MonadEnvironment
    - Juvix.Backends.LLVM.DSL
  other-modules:
    - Juvix.Interpreter.InteractionNet.NodeInterface

executables:
  juvix:
    source-dirs:      app
    main:             Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fwrite-ide-info
    dependencies:
      - juvix
      - optparse-applicative
      - ansi-wl-pprint
      - raw-strings-qq
      - yaml
      - aeson
      - haskeline
      - gitrev

tests:
  juvix-test:
    main:         Main.hs
    source-dirs:  test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - juvix
      - tasty
      - tasty-hunit
      - tasty-silver
      - tasty-quickcheck

benchmarks:
  juvix-bench:
    main:         Main.hs
    source-dirs:  bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - juvix
      - criterion
