name:                juvix
version:             0.0.0.0
github:              "cryptiumlabs/juvix"
license:             GPL-3
homepage:            https://github.com/cryptiumlabs/juvix#readme
synopsis:            Juvix smart contract compiler & toolkit
category:            Web3
description:         Please see the README on GitHub at <https://github.com/cwgoes/juvix#readme>
author:              Cryptium Labs
maintainer:          cwgoes@cryptium.ch, jeremy@cryptium.ch
copyright:           2018-2019 Cryptium Labs

extra-source-files:
- README.md

dependencies:
  - base >= 4.11 && < 5
  - protolude
  - text
  - mtl
  - containers
  - fgl
  - lens
  - parsec
  - capability >= 0.2.0.0
  - fgl-visualize
  - enummapset
  - turtle
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - NoMonomorphismRestriction
  - RankNTypes
  - LambdaCase
  - UnicodeSyntax
  - GADTs
  - ScopedTypeVariables
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - DataKinds
  - GeneralizedNewtypeDeriving
  - DefaultSignatures
  - QuasiQuotes
  - TypeOperators
  - MultiParamTypeClasses
  - MultiWayIf
  - TypeInType
  - DerivingVia
  - TypeApplications

ghc-options:
  - -ferror-spans
  - -Wall
  - -fno-warn-orphans
  - -fno-warn-name-shadowing
  - -j4

library:
  source-dirs: src
  dependencies:
    - directory
    - z3
  exposed-modules:
    - Juvix
    - Juvix.Core
    - Juvix.EAL
    - Juvix.EAL.Check
    - Juvix.EAL.EAL
    - Juvix.EAL.Solve
    - Juvix.EAL.Types
    - Juvix.EAL.Parser
    - Juvix.Utility
    - Juvix.Nets.Bohm
    - Juvix.Nets.Combinators
    - Juvix.Backends.Interface
    - Juvix.Backends.Env
    - Juvix.Backends.Graph
    - Juvix.Backends.Maps
    - Juvix.Bohm.Parser
    - Juvix.Bohm.Translation
    - Juvix.Bohm.Type
    - Juvix.Library
    - Juvix.Visualize.Dot
    - Juvix.Visualize.Graph
    - Juvix.Encoding.Encoding
    - Juvix.Encoding.Mendler
    - Juvix.Encoding.Scott
    - Juvix.Encoding.Types

executables:
  juvix:
    source-dirs:      app
    main:             Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - juvix
      - directory
      - optparse-applicative
      - ansi-wl-pprint
      - raw-strings-qq
      - yaml
      - aeson
      - haskeline
      - gitrev

tests:
  juvix-test:
    main:         Spec.hs
    source-dirs:  test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - juvix
      - tasty
      - tasty-hunit
      - temporary
      - raw-strings-qq
      - process
