name:                juvix
version:             0.0.0.0
github:              "cryptiumlabs/juvix"
license:             GPL-3
homepage:            https://github.com/cryptiumlabs/juvix#readme
synopsis:            Juvix smart contract language compiler, debugging toolkit, & stateful deployment system
category:            Web3
description:         Please see the README on GitHub at <https://github.com/cryptiumlabs/juvix#readme>
author:              Cryptium Labs
maintainer:          cwgoes@cryptium.ch, jeremy@cryptium.ch, marty@cryptium.ch, andy@cryptium.ch
copyright:           2018 Christopher Goes, 2018-2019 Cryptium Labs

extra-source-files:
- README.md

dependencies:
  - aeson
  - base >= 4.11 && < 5
  - Cabal
  - capability >= 0.2.0.0
  - directory
  - extensible-data
  - galois-field
  - lens
  - megaparsec
  - scientific
  - syb
  - temporary
  - wl-pprint-text
  ###########################
  # Libraries
  ###########################
  - standard-library
  - frontend
  - core
  - translate
  - michelson
  - plonk
  # - llvm
  # - interaction-net
  # - arithmetic-circuit
  # - InteractionNetIR
  ###########################
  # Dependency for OS
  ###########################
  - turtle
  - time
  - filepath
  ###########################
  # Dependency for Structs
  ###########################
  - text
  - mtl
  - containers
  - unordered-containers
  - hashable
  - fgl
  - fgl-visualize
  - bytestring

  ###########################
  # Dependency for Morley
  ###########################
  - morley


default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - NoMonomorphismRestriction
  - RankNTypes
  - LambdaCase
  - UnicodeSyntax
  - GADTs
  - ScopedTypeVariables
  - DeriveDataTypeable
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - DataKinds
  - GeneralizedNewtypeDeriving
  - DefaultSignatures
  - QuasiQuotes
  - TypeOperators
  - MultiParamTypeClasses
  - MultiWayIf
  - TypeInType
  - DerivingVia
  - TypeApplications
  - StandaloneDeriving
  - FunctionalDependencies
  - PatternSynonyms
  - TypeFamilies
  - ConstraintKinds
  - EmptyDataDeriving
  - TemplateHaskell
  - NamedFieldPuns
  - DisambiguateRecordFields
  - TupleSections
  - BlockArguments

when:
  condition: flag(incomplete-error)
  ghc-options:
    - -Werror=incomplete-patterns
    - -Werror=missing-fields
    - -Werror=missing-methods

flags:
  incomplete-error:
    description: >
      Incomplete patterns, missing record fields, and missing class methods are
      an error
    manual: true
    default: false

library:
  source-dirs: src
  dependencies:
    - derive-storable
    - derive-storable-plugin
    - jsonschema-gen
  exposed-modules:
    - Juvix
    - Juvix.Pipeline
    - Juvix.Core
    - Juvix.Core.Pipeline
    - Juvix.Encoding.Encoding
    - Juvix.Encoding.Mendler
    - Juvix.Encoding.Scott
    - Juvix.Encoding.Types
    - Juvix.Pipeline.Backend
  ghc-options:
    - -Wmissing-export-lists
    - -j
    - -static
    - -ferror-spans
    - -fno-warn-name-shadowing
    - -fno-warn-unused-matches
    - -fno-warn-unused-do-bind
    - -fwarn-tabs
    - -fwarn-incomplete-patterns
    - -fwarn-incomplete-uni-patterns
    - -fwarn-redundant-constraints
    - -fwarn-implicit-prelude
    - -fwarn-overflowed-literals
    - -fwarn-orphans
    - -fwarn-identities
    - -fwarn-dodgy-exports
    - -fwarn-dodgy-imports
    - -fwarn-duplicate-exports
    - -fwarn-overlapping-patterns
    - -fwarn-missing-fields
    - -fwarn-missing-methods
    - -fwarn-missing-signatures
    - -fwarn-missing-pattern-synonym-signatures
    - -fwarn-noncanonical-monad-instances
    - -fwarn-unused-imports
    - -fwarn-unused-pattern-binds
    - -fwarn-unused-type-patterns
    - -fwarn-unrecognised-pragmas
    - -fwarn-wrong-do-bind
    - -fwarn-hi-shadowing
    - -fwrite-ide-info
    - -optP-Wno-nonportable-include-path


executables:
  juvix:
    source-dirs:      app
    main:             Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aeson
      - ansi-wl-pprint
      - elliptic-curve
      - gitrev
      - haskeline
      - juvix
      - optparse-applicative
      - pretty-simple
      - raw-strings-qq
      - yaml

tests:
  juvix-test:
    main:         Main.hs
    source-dirs:  test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - juvix
      - tasty
      - tasty-hunit
      - tasty-silver
      - tasty-quickcheck
      - parsec
      - pretty-simple

benchmarks:
  juvix-bench:
    main:         Main.hs
    source-dirs:  bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - juvix
      - criterion
