resolver: lts-12.25

packages:
- .

extra-deps:
- idris-1.3.1
- terminfo-0.4.1.3
- wasm-1.0.0
- hevm-0.21
- ghci-pretty-0.0.2
- multiset-0.3.4.1
- readline-1.0.3.0
- restless-git-0.7
- s-cargot-0.1.4.0
- text-format-0.3.2
- tree-view-0.5
- HSH-2.1.3
- ipprint-0.6
- sr-extra-1.46.3.2
- Unixutils-1.54.1

allow-newer: true
