version: 2.1

jobs:
  setup_dependencies:
    docker:
      - image: cryptiumlabs/juvix-ci-2
    resource_class: xlarge
    steps:
      - checkout
      - restore_cache:
          name: Restore cached dependencies
          keys:
            - juvix-cache-v2-{{ checksum "package.yaml" }}
      - run:
          name: Build dependencies
          command: stack build -j8 --only-dependencies
          no_output_timeout: 1200
      - run:
          name: Build Juvix
          command: stack build -j8 --copy-bins --fast
      - persist_to_workspace:
          root: /root
          paths:
            - .
      - save_cache:
          name: Cache dependencies
          key: juvix-cache-v2-{{ checksum "package.yaml" }}
          paths:
            - "~/.stack"
            - ".stack-work"

  test_suite:
    docker:
      - image: cryptiumlabs/juvix-ci-2
    resource_class: xlarge
    steps:
      - attach_workspace:
          at: /root
      - run:
          name: Run tests
          command: stack test --fast -j8 --test-arguments "--hide-successes --ansi-tricks false"
          no_output_timeout: 1200

  check_formatting:
    docker:
      - image: cryptiumlabs/juvix-ci-2
    steps:
     - checkout
     - run:
         name: Check formatting
         command: ./scripts/check-formatting.sh

  check_org_gen:
    docker:
      - image: cryptiumlabs/juvix-ci-2
    steps:
     - checkout
     - run:
         name: Check org gen
         command: ./scripts/check-org-gen.sh

workflows:
  version: 2.1
  test-suite:
    jobs:
      - setup_dependencies
      - test_suite:
          requires:
            - setup_dependencies
      - check_formatting
      - check_org_gen
