[tool.poetry]
name = "ci"
version = "0.1.0"
description = ""
authors = ["Gianmarco Fraccaroli <gianmarco.fraccaroli@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.17.84"
"ruamel.yaml" = "^0.17.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
