resolver: lts-17.9

packages:
- .
- ../../StandardLibrary
- ../../Core
- ../../InteractionNet

extra-deps:
- llvm-hs-9.0.1
- llvm-hs-pure-9.0.0
- llvm-hs-pretty-0.6.2.0@sha256:4c600122965e8dff586bdca0044ec2b1896f2875c2da5ad89bbab9799c9697cd,1670
- capability-0.4.0.0@sha256:d86d85a1691ef0165c77c47ea72eac75c99d21fb82947efe8b2f758991cf1837,3345
- github: metastatedev/extensible-data
  commit: d11dee6006169cb537e95af28c3541a24194dea8

################################################################################
# LLVM dependencies
################################################################################
- derive-storable-0.2.0.0@sha256:a5bb3fb8feb76e95c713f3a5e401f86b7f622dd598e747cad4324b33933f27e1,2422
- derive-storable-plugin-0.2.3.0@sha256:11adeef08d4595cfdfefa2432f6251ba5786ecc2bf0488d36b74e3b3e5ca9ba9,2817

###############################
# For eac solver for Core
###############################
- github: cwgoes/haskell-z3
  commit: 889597234bcdf5620c5a69d3405ab4d607ba4d71

###############################
# For Interaction Net
###############################

- github: cryptiumlabs/jsonschema-gen
  commit: 0639cd166ec59a04d07a3a7d49bdf343e567000e

allow-newer: true
