resolver: lts-17.9

packages:
- .
- ../StandardLibrary
- ../Core

extra-deps:

########################
# General Dependencies #
########################
- capability-0.4.0.0@sha256:d86d85a1691ef0165c77c47ea72eac75c99d21fb82947efe8b2f758991cf1837,3345
- github: metastatedev/extensible-data
  commit: d11dee6006169cb537e95af28c3541a24194dea8
- github: jyp/prettiest
  commit: e5ce6cd6b4da71860c3d97da84bed4a827fa00ef

######################
# For the EAC Solver #
######################
- github: cwgoes/haskell-z3
  commit: 889597234bcdf5620c5a69d3405ab4d607ba4d71

