resolver: lts-17.3

packages:
- .
- ../../StandardLibrary
- ../../Core
- ../../Pipeline
- ../../Translate
- ../../Frontend

extra-deps:

########################
# General Dependencies #
########################
- capability-0.4.0.0@sha256:d86d85a1691ef0165c77c47ea72eac75c99d21fb82947efe8b2f758991cf1837,3345
- github: metastatedev/extensible-data
  commit: d11dee6006169cb537e95af28c3541a24194dea8

##################
# Fmt witherable #
##################
- fmt-0.6.1.2@sha256:405a1bfc0ba0fd99f6eb1ee71f100045223f79204f961593012f28fd99cd1237,5319
- witherable-0.3.5@sha256:6590a15735b50ac14dcc138d4265ff1585d5f3e9d3047d5ebc5abf4cd5f50084,1476
- witherable-class-0@sha256:91f05518f9f4af5b02424f13ee7dcdab5d6618e01346aa2f388a72ff93e2e501,775

######################
# For the EAC Solver #
######################
- github: cwgoes/haskell-z3
  commit: 889597234bcdf5620c5a69d3405ab4d607ba4d71

######################################################
# Shared Deps Between Arithmetic Circuits and Morley #
######################################################
- git: https://github.com/serokell/elliptic-curve.git
  commit: b8a3d0cf8f7bacfed77dc3b697f5d08bd33396a8
- git: https://github.com/serokell/pairing.git
  commit: cf86cf1f6b03f478a439703b050c520a9d455353
- git: https://github.com/serokell/galois-field.git
  commit: 576ba98ec947370835a1f308895037c7aa7f8b71

################################
# Morley Specific dependencies #
################################
- git: https://gitlab.com/obsidian.systems/tezos-bake-monitor-lib.git
  commit: 9356f64a6dfc5cf9b108ad84d1f89bcdc1f08174
  subdirs:
    - tezos-bake-monitor-lib

#########################################################
# Git depdencies caused by Morley specific dependencies #
#########################################################
- morley-1.14.0@sha256:70a9fc646bae3a85967224c7c42b2e49155461d6124c487bbcc1d825111a189d,9682
- morley-prelude-0.4.0@sha256:7234db1acac9a5554d01bdbf22d63b598c69b9fefaeace0fb6f765bf7bf738d4,2176
- base58-bytestring-0.1.0
- hex-text-0.1.0.0
- show-type-0.1.1
- named-0.3.0.1@sha256:2975d50c9c5d88095026ffc1303d2d9be52e5f588a8f8bcb7003a04b79f10a06,2312
- cryptonite-0.27
- uncaught-exception-0.1.0
- tasty-hunit-compat-0.2.0.1
- with-utf8-1.0.2.2@sha256:42eed140390b3e93d9482b084d1d0150e8774667f39c33bd47e84815751fad09,3057

#########################################################################################
# Git depdencies caused by Morley specific dependencies that are speicific to Michelson #
#########################################################################################
- git: https://github.com/int-index/caps.git
  commit: c5d61837eb358989b581ed82b1e79158c4823b1b
- git: https://github.com/serokell/base-noprelude.git
  commit: 87df0899801dcdffd08ef7c3efd3c63e67e623c2

######################
# Visualizing graphs #
######################
- fgl-visualize-0.1.0.1@sha256:e682066053a6e75478a08fd6822dd0143a3b8ea23244bdb01dd389a266447c5e,995

#####################################
# Standard Library Extra Dependency #
#####################################
- github: phile314/tasty-silver
  commit: f1f90ac3113cd445e2a7ade43ebb29f0db38ab9b
- tasty-1.4.1@sha256:69e90e965543faf0fc2c8e486d6c1d8cf81fd108e2c4541234c41490f392f94f,2638

