name:                translate
version:             0.1.0.0
github:              "githubuser/Translate"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Translate#readme>

dependencies:
- base >= 4.11 && < 5
- standard-library
- core
- frontend
- extensible-data
- unordered-containers

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - NoMonomorphismRestriction
  - RankNTypes
  - LambdaCase
  - UnicodeSyntax
  - GADTs
  - DerivingVia
  - MultiWayIf
  - DataKinds
  - TypeApplications
  - ConstraintKinds
  - PatternSynonyms
  - FlexibleContexts
  - FlexibleInstances
  - QuasiQuotes
  - TemplateHaskell
  - TypeFamilies
  - NamedFieldPuns
  - DisambiguateRecordFields
  - TupleSections
  - DeriveGeneric
  - DeriveDataTypeable
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving

library:
  source-dirs: src

tests:
  Translate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - translate
