resolver: lts-15.16

packages:
- .
- ../StandardLibrary
- ../Frontend
- ../Core
- ../Backends/Plonk

extra-deps:
- capability-0.3.0.0@sha256:0f198c6523b940517670c0ba62e4ee19622c3bb3d8c1b80293e5a882a150b41f,3262
- github: metastatedev/extensible-data
  commit: d11dee6006169cb537e95af28c3541a24194dea8

####################################
# For testing with Circuit backend
####################################
- github: adjoint-io/pairing
  commit: 2ef8ba869608432f55e32afc385b7fa75d4d1742
- github: adjoint-io/elliptic-curve
  commit: 52b7eba38db0b3aa3619f2916c518f8f3ee63aaf
- github: adjoint-io/galois-field
  commit: 95fc86b61c573518ff6a1ab1b9f23301482b257
###############################
# For eac solver in core
###############################
- github: cwgoes/haskell-z3
  commit: 889597234bcdf5620c5a69d3405ab4d607ba4d71