name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: cryptiumlabs/juvix-ci
    name: Checkout, build, test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build dependencies
      run: stack build -j2 --only-dependencies +RTS -N2 -qg 
    - name: Build Juvix
      run: stack build --copy-bins --fast
    - name: Test Juvix
      run: stack test --fast --jobs=1 --test-arguments "--hide-successes --ansi-tricks false" +RTS -N4 
